### ISSUE TITLE
[update-collection-v3] Yaml aliases are expanded

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-tools#444]
Yaml aliases are expanded, which results in duplication and harder comparison of changes.

Input:

```yaml
sumologic:
  node1: &blueprint
    key1: value1
    key2: value2
  node2:
    <<: *blueprint
    key3: value3
```

Expected output:

```yaml
sumologic:
  node1: &blueprint
    key1: value1
    key2: value2
  node2:
    <<: *blueprint
    key3: value3
```

Actual output:

```yaml
sumologic:
  node1:
    key1: value1
    key2: value2
  node2:
    key1: value1
    key2: value2
    key3: value3
```
