### ISSUE TITLE
[update-collection-v3] `otelagent`, `otelcol`, `otelgateway` configuration is lost during migration

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-tools#445]
Version: v2.17.0

According to this mention in chart v3 [changelog](https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/CHANGELOG.md):

> - move parameters from otelagent.* to otelcolInstrumentation.*
> - move parameters from otelgateway.* to tracesGateway.*
> - move parameters from otelcol.* to tracesSampler.*

I would assume any keys under the `otelagent` key - like `otelagent.daemonset.*` - will be migrated under `otelcolInstrumentation` key. This does not seem to be the case - the values are simply dropped.

I know there's a warning displayed in command output, but it's hardly helpful (especially combined with https://github.com/SumoLogic/sumologic-kubernetes-tools/issues/435):

> WARNING! Tracing config migrated to v3, please check the output file. For more details see documentation: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/docs/v3-migration-doc.md#tracinginstrumentation-changes

The link in this warning is actually outdated.
Other than that, the docs at https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v3.0.0/docs/v3-migration-doc.md#tracing-migration don't mention the need to manually migrate any specific properties, like `otelagent.daemonset.resources` for instance.

Input:

```yaml
sumologic:
  accessId: xxx
  accessKey: yyy

otelagent:
  daemonset:
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
    tolerations:
      - effect: NoSchedule
        operator: Exists
    priorityClassName: system-node-critical

otelcol:
  deployment:
    resources:
      requests:
        memory: 123Mi
        cpu: 456m

otelgateway:
  deployment:
    resources:
      requests:
        memory: 789Mi
        cpu: 987m
```

Expected output:

```yaml
sumologic:
  accessId: xxx
  accessKey: yyy

otelcolInstrumentation:
  daemonset:
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
    tolerations:
      - effect: NoSchedule
        operator: Exists
    priorityClassName: system-node-critical

tracesSampler:
  deployment:
    resources:
      requests:
        memory: 123Mi
        cpu: 456m

tracesGateway:
  deployment:
    resources:
      requests:
        memory: 789Mi
        cpu: 987m
```

Actual output:

```yaml
sumologic:
  accessId: xxx
  accessKey: yyy
```
